
language: julia

os: 
  - linux
  - osx

julia: 
  - nightly
  - 1.5
  - 1.6


notifications:
  email: false


codecov: true

matrix:
  allow_failures:
    - julia: nightly

after_success: 
  - "julia -e 'import Pkg; Pkg.add(\"Coverage\"); using Coverage; Coveralls.submit(Coveralls.process_folder())'"