name = "TransitionalMCMC"
uuid = "5bc637a6-1a46-43ed-8ea7-ee39cc1921ce"
authors = ["Ander Gray <ander.gray@liverpool.ac.uk>", "Adolphus Lye <Adolphus.Lye@liverpool.ac.uk>"]
version = "0.4.2"

[deps]
CovarianceEstimation = "587fd27a-f159-11e8-2dae-1979310e6154"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
CovarianceEstimation = "0.2.5"
Distributions = "0.24, 0.25"
StatsBase = "0.33"
TimerOutputs = "0.5"
julia = "1"
